apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingest-router.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingest-router.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.routerConfig | toPrettyJson | nindent 4 }}
