apiVersion: v1
kind: Secret
metadata:
  name: msk-scram-credentials
  namespace: header-router-msk
type: Opaque
stringData:
  username: "<replace-with-msk-scram-username>"
  password: "<replace-with-msk-scram-password>"
